### ISSUE TITLE
[Feature request] Command line version

### ISSUE THREAD

**Issue by bipsendk** [syue87/GCodeAnalyser#10]
It would be nice with a command line version, where the input filename would be taken from the command line (and maybe a parameter to specify the configuration parameters like accel/jerk settings and so on in an xml/json file) - and the the estimated printing time could be written to stdout (or an output file).

The will make integration in e.g. Simplify3D somewhat easier - to have something create a pop-up window with the estimated print time (which for this analyzer is pretty accurate).

**Comment by syue87** [comment]
Currently everything is computed locally in your browser with JavaScript. So it is not possible to run the program without the browser.
