### ISSUE TITLE
Firmware retraction handling loses layer change

### ISSUE THREAD

**Issue by richfelker** [syue87/GCodeAnalyser#14]
When firmware retract is used for the retraction across layer change, the analyzer loses it, combining the whole print into one logical layer. The cause of the problem is:

https://github.com/syue87/GCodeAnalyser/blob/49bccddc9d12166f083dee3a649303dcea95b75c/js/gcodeProcessor.js#L952

where any change to Z that occured while retracted is thrown away and replaced by the old Z at the time of retraction. Instead of `gcode.coord[2] = this.zBeforeFirmwareRetractZhop` it needs to be `gcode.coord[2] -= this.firmwareRetractZhop`. The wrong code just seems to be based on a misunderstanding of `G10`/`G11` semantics; `G11` doesn't save a Z coordinate stored by `G10`; it just reverts the relative change.

**Comment by richfelker** [comment]
Indeed that fixes it here.

**Comment by syue87** [comment]
Thank you so much for reporting this issue and providing the fix. I will update the website soon.

**Comment by syue87** [comment]
Fix is in place. Please let me know if there is any problem. Thank you.

**Comment by richfelker** [comment]
It now works. Thanks for the quick fix!
