### ISSUE TITLE
Linear advance

### ISSUE THREAD

**Issue by Brandoskey** [syue87/GCodeAnalyser#2]
I think there may be an issue with linear advance support? All my gcode I upload with linear advance enabled looks very strange in the layer view. Looks like there's a lot of missing lines or thin lines. Perhaps this is actually intended?

**Comment by syue87** [comment]
The program doesn't know whether linear advance is used. It just draws what's represented by the gcodes. 
Linear advance works by start extruding early to build up nozzle pressure, and stop or slow down extruding early(which caused the missing or thin lines in your case) to release nozzle pressure. What you are seeing is effect of linear advance so yes it is expected.

**Comment by Brandoskey** [comment]
Good to know. Does linear advance affect the time estimation at all? I'm having difficulty getting accurate times on my Prusa MK3. My Maker Select Plus was spot on.

**Comment by syue87** [comment]
Linear advance shouldn’t affect time estimation. The first thing I would check is the parameters. Marlin uses mm/min, my program uses mm/sec. Have you divided the marlin value by 60 for the my program?

**Comment by syue87** [comment]
@Brandoskey I don't know if you are still having accuracy issueon your estimation, but if you are using M220(speed multiplier) or M221(extrusion multiplier) commands in your gcode, I just fix a problem that could hugely affect estimation accuracy.
