### ISSUE TITLE
[Feature Request] Add filament density setting for calculating the raw material usage in grams

### ISSUE THREAD

**Issue by magkopian** [syue87/GCodeAnalyser#4]
Slic3r has an option for specifying the density for a particular filament, which combined with the filament diameter allows it to estimate how much filament is going to be used in grams for a print. It would be nice if GCodeAnalyser was able to calculate that as well.

**Comment by syue87** [comment]
@magkopian Sure, It would be good to know the usage in gram. I will add it.

**Comment by syue87** [comment]
I thought about it. I don't think many people know the exact density of their filament, so I've added a display for filament usage in cm^3. Since most filament is around 1g/cm^3, it's a good approximation for the weight.
