### ISSUE TITLE
[Feature Request] Add a movement-distance Histogram

### ISSUE THREAD

**Issue by LittleHelper00** [syue87/GCodeAnalyser#9]
It would be beneficial to have also an histogram showing the distrubution of all the movement-distance

**Comment by syue87** [comment]
I can see where you are going with this, but it's hard to define what a movement is. If you define a straight line as a single movement, a smooth curve would have tens or hundreds of movements. To do this properly the program would have to calculate the angle between every segments. For now, it doesn't worth the effort to add this feature.
